/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiLink: typeof import('./theme/components/ApiLink.vue')['default']
    ExampleFunctions: typeof import('./theme/components/ExampleFunctions.vue')['default']
    FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
    FunctionInfo: typeof import('./theme/components/FunctionInfo.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
    NonProprietary: typeof import('./theme/components/NonProprietary.vue')['default']
    ReactiveVscode: typeof import('./theme/components/ReactiveVscode.vue')['default']
    ReactiveVscode2: typeof import('./theme/components/ReactiveVscode2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ApiLink: typeof import('./theme/components/ApiLink.vue')['default']
  const ExampleFunctions: typeof import('./theme/components/ExampleFunctions.vue')['default']
  const FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
  const FunctionInfo: typeof import('./theme/components/FunctionInfo.vue')['default']
  const FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
  const NonProprietary: typeof import('./theme/components/NonProprietary.vue')['default']
  const ReactiveVscode: typeof import('./theme/components/ReactiveVscode.vue')['default']
  const ReactiveVscode2: typeof import('./theme/components/ReactiveVscode2.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}